@extends('admin.dashboard')

@section('content')
<h2 style="color: #666; font-size: 1.4rem; margin-bottom: 10px;">Admin "Boxes" Menu</h2>
<div class="row" style="margin: 10px;">
    <div class="col-md-9" style="padding-right:0;">
        <table style="width:100%; border-collapse:collapse; font-size:14px;">
            <thead>
                <tr style="background:#eaeaea;">
                    <th style="padding:4px; border:1px solid #ccc; text-align:left;">Boxes</th>
                    <th style="padding:4px; border:1px solid #ccc; text-align:left;">Status</th>
                    <th style="padding:4px; border:1px solid #ccc; text-align:left;">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr style="background:#f9f9e9;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Email_template</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Forum_manager</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#e9ecf7;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Import_jobs</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Jobs</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#f9f9e9;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Jobseekers</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Localization</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#e9ecf7;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Messages</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Newsletter</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#f9f9e9;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Online_services</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Orders</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#e9ecf7;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Print</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Rate_card</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#f9f9e9;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Recruiters</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Reports</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#e9ecf7;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>School</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Search</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#f9f9e9;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Seo</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Setting</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#e9ecf7;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Start_business</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Themes</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr style="background:#f9f9e9;"><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>Tools</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td><span style="color:#e2c200; margin-right:6px;">&#128193;</span>University</td><td><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative; margin-right:2px;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#f99; position:absolute; top:3px; left:3px;"></span></span><span style="display:inline-block; width:16px; height:16px; border-radius:50%; background:#fff; border:1px solid #aaa; position:relative;"><span style="display:block; width:10px; height:10px; border-radius:50%; background:#090; position:absolute; top:3px; left:3px;"></span></span></td><td><span style="font-size:16px; color:#444;">&#9432;</span></td></tr>
                <tr><td colspan="3" style="font-size:13px; color:#444; text-align:left;">File(s): 28</td></tr>
            </tbody>
        </table>
    </div>
    <div class="col-md-3" style="padding-left:0;">
        <div style="border:1px solid #ccc; background:#fff; margin-top:0;">
            <div style="background:#f2f2f2; font-weight:bold; padding:6px 10px; border-bottom:1px solid #ccc; font-size:15px;">Boxes: Administrator</div>
            <div style="padding:6px 10px;">
                <button class="btn btn-light border mb-2" style="font-weight:bold; font-size:15px; padding:2px 18px;">Store Files</button>
                <div style="font-size:13px; color:#444; margin-bottom:6px;">Simply click the green button to install the box or the red button to uninstall it.</div>
                <div style="font-size:13px; color:#b00; font-weight:bold;">WARNING: If you uninstall the box, all files stored in also will be remove!</div>
            </div>
        </div>
    </div>
</div>
@endsection 